package main;

import java.util.ArrayList;
import java.util.Arrays;

public class MessageLister 
{
	static ArrayList<String> messages = new ArrayList<String>(Arrays.asList(
			"You are the one",
			"I carry you with me always",
			"Nothing is worse than being apart",
			"I think of you and smile",
			"Life is a little less difficult because of you",
			"You are the love of my life",
			"I love to laugh with you",
			"You are my best friend",
			"Love stories always happened to someone else, until now...",
			"You make me feel special",
			"Thinking of you and smiling",
			"I will go anywhere with you",
			"You are sexy",
			"When I touch you, I feel content",
			"We created something special to build from",
			"My heart actually skips a beat when I see you",
			"You hold the key to my heart",
			"Together is the best place to be",
			"You and I are the same type of strange",
			"You are and always have been my love",
			"I vow to fiercely love you in all your forms, now and forever",
			"I promise to never forget that this is a once in a lifetime love",
			"Kiss me. Kiss me as if it were the last time",
			"You make my heart sing",
			"I never meant to fall in love",
			"You take my breath away",
			"I love you more",
			"Love finds a way",
			"I carry you in my heart",
			"I love being with you",
			"Your smile warms my heart",
			"You are in my thoughts, always",
			"I crave you more than chocolate",
			"I am yours, today and always",
			"You are the puzzle piece that has been missing all along",
			"You warm my heart",
			"I am yours",
			"All I want is your arms around me",
			"I smile whenever I think about you",
			"You make me happy",
			"You spoke to my heart",
			"Your presence is a whisper with me all the time",
			"You are the best thing in my life",
			"You speak to my soul",
			"When I think of our future, I only see you",
			"You are my future",
			"You are everything that I have always wanted",
			"When I met you, everything made sense",
			"You will never age for me, nor fade, nor die",
			"I wish I had done everything on earth with you",
			"I miss you deeply, unfathomably, senselessly, terribly",
			"You are worth every mile between us",
			"You will always be with me, like a hand print on my heart",
			"I never thought that being apart from you would be this hard for me, but it is... I miss you",
			"When I whisper, I miss you, I believe that you can hear me",
			"Our souls will always be connected",
			"I hope you are missing me in the same way that I am missing you",
			"I want to make love with my tongue, and whisper kisses, through your mind, until your body comes, undone Body language",
			"Just when I thought I couldn't be any happier, I see you and all that changes again",
			"Shakespeare would have been right if he said a life without love is miserable without you",
			"I love you",
			"And at my funeral, don't be sad for us my love, I have a soul that will fight lifetimes in the dark, waiting for your light to come",
			"When I think of it, you are my favorite hello and hardest goodbye",
			"My heart skips a beat every time I set my eyes on you",
			"You are my sunshine baby",
			"My heart for you will never break",
			"My smile for you will never fade",
			"My love for you will never end",
			"I love you a million more",
			"You have this incredible way of making my heart happy",
			"You are my treasure always",
			"I want to nibble on your neck and make your goosebumps, a mess",
			"I never knew that I was rich until I met you",
			"You are the most expensive gift in my life",
			"When our lips finally touch, the universe will darken the sky, lighting up a parade of stars, as we kiss into the night",
			"Before you, I looked at life as at the combination of black and white colors with grey shadows. With you, I finally see the bright colors that make me happy and bring love into my every day",
			"If I were a cupcake, you would be the delicious vanilla filling to me. Without it, the cake would lose its fantastic flavor. Without you, I would lose myself",
			"I do not need a box of chocolate candies because I already have you",
			"You sweeten my days and coat my nights with sugar",
			"I adore you like a bee loves the flowers",
			"You are my honey, my dream, my everything",
			"Attraction brought us closer. Love's gonna keep us that way, forever",
			"The only word to describe you, is MINE and the only word to describe us, is forever",
			"To survive, humans need air, food, and water. I just need your hugs, smiles, and kisses",
			"I'm having one of those days that make me realize how lost I'd be without you",
			"I only saw you for a second, but it made my day",
			"There are only two times that I want to be with you... Now and Forever",
			"Your love is the only armor I need to fight all of life's battles",
			"If I could be anything I would be your tear, so I could be born in your eye, live down your cheek and die on your lips",
			"Every time we cuddle turns into my life,s newest priceless memory",
			"You are my dil",
			"You are my jan",
			"You are my hobi",
			"You are my wife",
			"I love you to the moon and back not to earth no to the sunnn",
			"Be ready to be kidnapped and be loved",
			"You are mine and I want every peice of uuu",
			"Your smile is a mirror to my happiness",
			"Spending the night and calls with you is my faviourt advanture",
			"Seeing u after every shower blushing is muahhh",
			"May your day be as bright as you make mine. Happy new day and yearrrrrr"));
}
